version: '3.8'

services:
  frontend:
    image: vue-frontend:latest
    build: ./frontend
    container_name: vue-frontend
    working_dir: /frontend
    volumes:
      - /frontend/node_modules/
      - ./frontend:/frontend
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development

  backend:
    image: go-backend:latest
    build: ./backend
    container_name: go-backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8080
    environment:
      - DB_TYPE=mongo
      - MONGO_URI=mongodb://gdsf:gdsf@db:27017
      - TOKEN_HASHING_KEY='ZUDx!8@76Dri!TI#v1O#Zh!IrzS%8FJZtCNmxqMo'
      - ACCESS_TOKEN_LIFETIME_MINS=5
      - REFRESH_TOKEN_LIFETIME_DAYS=15
      - GOOGLE_CLOUD_STORAGE_OAUTH2_TOKEN=sal;kdjfi;oejflaijliasj
    command: gin --appPort 8080 -i run .

  db:
    image: 'mongo'
    container_name: 'gdsf-db'
    environment:
      - MONGO_INITDB_DATABASE=gdsf
      - MONGO_INITDB_ROOT_USERNAME=gdsf
      - MONGO_INITDB_ROOT_PASSWORD=gdsf
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'

volumes:
  mongo-volume: